[package]
name = "lepet-ext"
version = "0.1.0"
edition = "2021"

[lib]
name = "lepet_ext"
crate-type = ["cdylib"]

[dependencies]
pyo3-ffi = { version = "0.21.2", features = ["extension-module"] }
libc = "*"

[profile.release]
opt-level = 3
